name: demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3

  # Authentication
  google_sign_in: ^6.0.0

  # HTTP & Files
  http: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  flutter_image_compress: ^2.1.0
  archive: ^3.3.7
  image_picker_for_web: ^3.0.3
  camera: ^0.11.0+2
  camera_web: ^0.3.2+5

  # Localization
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.3

  # Audio & Media
  audioplayers: ^6.5.1

  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  flutter_map_location_marker: ^8.1.0
  geolocator: ^11.0.0
  geojson_vi: ^2.0.0

  # UI
  table_calendar: ^3.0.8
  google_fonts: ^5.0.0

  # Permissions
  permission_handler: ^11.3.0

  # Utilities
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.jpg
    - assets/images/app_logo.png
    - assets/langs/
